import Sidebar from '@/components/dashbaord/Sidebar'
import Header from '@/components/dashbaord/Header'
export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};
export default function DashboardLayout({
    children
}
) {
    return (
        <div className="container w-[800] mx-auto py-8">
            <div className="flex">
                <Sidebar />
                <div className="flex-1">
                    <Header />
                    <main className="p-4">
                        {children}
                    </main>
                </div>
            </div>
        </div>
    )
}